[Xcode] Remove redundant dependency
That dependency is apparently required to include cassette in pubsdk as
it does not work through cocoapods:

       ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Testing failed:
    	Undefined symbol: _OBJC_METACLASS_$_CASFileObjectQueue
    	Undefined symbol: _OBJC_CLASS_$_CASObjectQueue
    	Undefined symbol: _OBJC_CLASS_$_CASFileObjectQueue
    	Testing cancelled because the build failed.

Unfortunately that does not explains:

    objc[96860]: Class CASError is implemented in both /Users/jenkins/workspace/pub-sdk-fuji-pre-submit/build/DerivedData/Build/Products/Release-iphonesimulator/pubsdk.framework/pubsdk (0x123813c58) and /Users/jenkins/workspace/pub-sdk-fuji-pre-submit/build/DerivedData/Build/Products/Release-iphonesimulator/iTestHostApp.app/PlugIns/pubsdkTests.xctest/pubsdkTests (0x121d56578). One of the two will be used. Which one is undefined.


Change-Id: I19f1b5c04b69c496f48096065e967b9ef68502e0
JIRA: EE-882

Former-commit-id: 10220f7ce07a31af84b77e2f0361f18382529cbf